// GENERATED by scripts/wallet-demo-sync.mjs from board/lib/wallet — edit there, not here.
// The stand-in provider's own pages.
//
// The real flows leave the Exchange: identity is checked on the provider's
// page, a card is typed into the provider's page, and a European bank asks its
// customer to approve a payment on the bank's page. These pages stand in for
// those, so the wallet's hand-offs and returns are exercised exactly as they
// will be — and they say plainly, in the largest type on them, that they are a
// test and that nothing typed here would go anywhere.

const esc = (s) => String(s ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));

const COPY = {
  kyc: { title: "Confirm your identity", body: "On the real provider's page you would photograph your ID card or passport and take a selfie. The provider checks them and tells the Exchange only whether you passed.", approve: "Pass the check", decline: "Fail the check" },
  source: {
    card: { title: "Connect a card", body: "On the real page you would type your card number here, on the provider's page. The Exchange would only ever see the last four digits.", approve: "Connect test card", decline: "Cancel" },
    bank: { title: "Connect a bank account", body: "On the real page you would choose your bank and log in to it. Your bank shares the account with the provider, not your password.", approve: "Connect test bank", decline: "Cancel" },
    paypal: { title: "Connect PayPal", body: "On the real page you would log in to PayPal and approve the Exchange.", approve: "Approve test PayPal", decline: "Cancel" },
    wechat: { title: "Connect WeChat Pay", body: "On the real page you would approve the Exchange inside WeChat.", approve: "Approve test WeChat Pay", decline: "Cancel" },
  },
  sca: { title: "Your bank asks you to approve this payment", body: "European card payments usually need the bank's own approval. On the real page this is your bank, or a tap in your banking app.", approve: "Approve payment", decline: "Refuse payment" },
};

export function providerPage(s) {
  if (!s || s.flow === "gone") {
    return shell("Link expired", `<p>This test page has already been used or has expired.</p><p><a href="/wallet">Back to your wallet</a></p>`);
  }
  const t = s.flow === "source" ? COPY.source[s.sourceKind] : COPY[s.flow];
  if (!t) return providerPage(null);
  const amount = s.flow === "sca" && s.amount ? `<p class="amt">${esc((s.amount / 100).toFixed(2))} ${esc(s.currency)}</p>` : "";
  return shell(t.title, `
    <p class="badge" role="note">TEST PROVIDER — nothing typed here goes anywhere, and no money moves</p>
    <h1>${esc(t.title)}</h1>
    ${amount}
    <p>${esc(t.body)}</p>
    <form method="post">
      <button name="choice" value="approve" class="go">${esc(t.approve)}</button>
      <button name="choice" value="decline" class="no">${esc(t.decline)}</button>
    </form>`);
}

function shell(title, inner) {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="robots" content="noindex">
<title>${esc(title)} · Test provider</title>
<style>
  :root{color-scheme:light dark;--bg:#F4F6F2;--ink:#17201A;--muted:#55605A;--line:#D9DED8;--go:#1F7A4D;--go-ink:#fff;--warn:#FFF3CD}
  @media (prefers-color-scheme:dark){:root{--bg:#101512;--ink:#E8EEEA;--muted:#A5B0AA;--line:#27302B;--go:#3FB27A;--go-ink:#08110C;--warn:#3A3118}}
  body{margin:0;background:var(--bg);color:var(--ink);font:17px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;padding:24px 18px}
  main{max-width:30rem;margin:0 auto;display:grid;gap:14px}
  .badge{background:var(--warn);border:1px solid var(--line);border-radius:10px;padding:10px 12px;font-weight:700;font-size:15px}
  h1{margin:6px 0 0;font-size:24px;line-height:1.25}
  .amt{font-size:32px;font-weight:700;margin:0}
  p{margin:0;color:var(--muted)}
  form{display:grid;gap:10px;margin-top:8px}
  button{font:inherit;font-weight:700;border-radius:12px;padding:14px;border:1px solid var(--line);cursor:pointer}
  .go{background:var(--go);color:var(--go-ink);border-color:var(--go)}
  .no{background:transparent;color:var(--ink)}
  button:focus-visible,a:focus-visible{outline:3px solid var(--go);outline-offset:2px}
  a{color:var(--go)}
</style></head><body><main>${inner}</main></body></html>`;
}
